### ISSUE TITLE
[bug] Update/Download Queued in incorrect position

### ISSUE THREAD

**Issue by pointydev** [AikoMidori/steam-library#1]
Heya,

When a game has an update queued or is in the process of being downloaded, it gets borked. See the screenshot below:

![](https://pointy.needs-to-s.top/51Dw2VR.png)

I suspect this may also be the case with cloud sync, but I haven't looked that far into it.

Thanks,
Elliott

**Comment by AikoMidori** [comment]
@PointyDev it get's borked how? if you're talking about the title's position being pushed to the right, then that's steam's default way of doing so.

There would be a progress bar spinner left to the name originally and that's why it's dis-positioned.
But since i removed game icons by default, it looks a bit odd.

But i appreciate you sending the issue, i'll do my best to correct it.

**Comment by pointydev** [comment]
Yeah I re-enabled the icons and all looks fine, but yeah a correction would be great.

![](https://pointy.needs-to-s.top/7eDrgjd.png)

**Comment by AikoMidori** [comment]
Updating icon has been fixed in latest release. will change colors later.

**Comment by pointydev** [comment]
Seems to display correctly both with icons enabled and disabled now, thanks for the fix.

![](https://pointy.needs-to-s.top/85AQqDG.png)
![](https://pointy.needs-to-s.top/2UPY86Q.png)
